base_url = "https://kitmatheinfo.de/"
title = "KIT Mathe/Info Discordserver"
description = "Inoffizieller Discordserver f√ºr Informatik- und Mathematikstudenten des KIT"

compile_sass = true
minify_html = true
build_search_index = false

[markdown]
highlight_code = true
external_links_no_referrer = true
smart_punctuation = true

[extra]
social_image = "https://cdn.discordapp.com/icons/501365485837877268/a_830c17a8082accf987eb892b335c4721.webp?size=128"
discord_invite = "https://discord.com/invite/kit"
github_repo = "https://github.com/chrisliebaer/kitmatheinfo-website"