base_url = "https://kitmatheinfo.de/"
title = "KIT Mathe/Info Discordserver"
description = "Inoffizieller Discordserver f√ºr Informatik- und Mathematikstudenten des KIT"

compile_sass = true
minify_html = true
build_search_index = false

[markdown]
highlight_code = true
external_links_no_referrer = true
smart_punctuation = true

[extra]
social_image = "https://kitmatheinfo.de/icon/jMmYM5b3jT"
discord_invite = "https://discord.gg/jMmYM5b3jT"
github_repo = "https://github.com/chrisliebaer/kitmatheinfo-website"
